package com.chemsys.dto

import java.math.BigDecimal
import java.time.LocalDate
import java.util.UUID

/**
 * DTOs for comprehensive reporting features
 */

// ==================== Financial Report ====================

data class FinancialReportDto(
    val startDate: LocalDate,
    val endDate: LocalDate,
    val totalRevenue: BigDecimal,
    val totalCost: BigDecimal,
    val grossProfit: BigDecimal,
    val grossProfitMargin: Double,
    val totalSales: Long,
    val totalCreditSales: BigDecimal,
    val totalCashSales: BigDecimal,
    val creditPaymentsReceived: BigDecimal,
    /** Total expenses in the period (for the selected branch or all branches). */
    val totalExpenses: BigDecimal,
    /** Gross profit minus total expenses. */
    val grossProfitAfterExpense: BigDecimal,
    /** Expense as percentage of revenue (0 if no revenue). */
    val expenseAsPercentOfRevenue: Double,
    val revenueByPaymentMethod: List<PaymentMethodRevenueDto>,
    val dailyRevenue: List<DailyRevenueDto>
)

// ==================== Inventory Report ====================

data class InventoryReportDto(
    val totalItems: Long,
    val totalQuantity: Long,
    val totalStockValue: BigDecimal,
    val totalCostValue: BigDecimal,
    val lowStockItems: List<LowStockItemDto>,
    val expiringItems: List<ExpiringItemDto>,
    val outOfStockItems: List<OutOfStockItemDto>
)

data class LowStockItemDto(
    val productId: String,
    val productName: String,
    val currentStock: Long,
    val minStockLevel: Long,
    val stockValue: BigDecimal
)

data class ExpiringItemDto(
    val productId: String,
    val productName: String,
    val quantity: Long,
    val expiryDate: LocalDate,
    val daysUntilExpiry: Int,
    val stockValue: BigDecimal
)

data class OutOfStockItemDto(
    val productId: String,
    val productName: String,
    val lastRestockDate: LocalDate?
)

// ==================== Variance Report ====================

data class VarianceReportDto(
    val startDate: LocalDate,
    val endDate: LocalDate,
    val totalExpectedUsage: Long,
    val totalActualQuantity: Long,
    val totalVarianceQuantity: Long,
    val totalInventoryVariance: BigDecimal,
    val significantVariances: List<VarianceItemDto>
)

data class VarianceItemDto(
    val productId: String,
    val productName: String,
    val expectedQuantity: Long,
    val actualQuantity: Long,
    val varianceQuantity: Long,
    val varianceValue: BigDecimal,
    val variancePercentage: Double
)

// ==================== VAT Report ====================

data class VatReportDto(
    val startDate: LocalDate,
    val endDate: LocalDate,
    val totalOutputVat: BigDecimal,  // VAT collected from sales
    val totalInputVat: BigDecimal,   // VAT paid on purchases
    val netVatPayable: BigDecimal,   // Output VAT - Input VAT
    val totalSalesExcludingVat: BigDecimal,
    val totalSalesIncludingVat: BigDecimal,
    val totalPurchasesExcludingVat: BigDecimal,
    val totalPurchasesIncludingVat: BigDecimal,
    val vatByClassification: List<VatClassificationDetailDto>,
    val salesByTaxCategory: List<SalesByTaxCategoryDto>,
    val purchasesByTaxCategory: List<PurchasesByTaxCategoryDto>
)

data class VatClassificationDetailDto(
    val classification: String,
    val vatRate: BigDecimal,
    val totalSalesAmount: BigDecimal,
    val vatCollected: BigDecimal,
    val totalPurchasesAmount: BigDecimal,
    val vatPaid: BigDecimal,
    val netVat: BigDecimal
)

data class SalesByTaxCategoryDto(
    val classification: String,
    val vatRate: BigDecimal,
    val numberOfTransactions: Long,
    val totalAmount: BigDecimal,
    val totalVat: BigDecimal,
    val amountIncludingVat: BigDecimal
)

data class PurchasesByTaxCategoryDto(
    val classification: String,
    val vatRate: BigDecimal,
    val numberOfTransactions: Long,
    val totalAmount: BigDecimal,
    val totalVat: BigDecimal,
    val amountIncludingVat: BigDecimal
)

// ==================== User Performance Report ====================

/**
 * Performance metrics for a single user (cashier/manager) over a date range.
 * Used in the User Performance report to show revenue, profit, sales count, and commission per user.
 */
data class UserPerformanceDto(
    val userId: UUID,
    val userName: String,
    val email: String?,
    val role: String,
    /** Total sale revenue (sum of totalAmount) for this user in the period. */
    val totalRevenue: BigDecimal,
    /** Total profit (revenue minus cost of goods sold) generated by this user in the period. */
    val totalProfit: BigDecimal,
    /** Number of completed sales in the period. */
    val salesCount: Long,
    /** Commission earned: 15% of profit (selling price minus cost) per line item. */
    val commission: BigDecimal
)

/**
 * Report payload for user performance (cashiers/managers) over a date range.
 * Supports filtering by branch; used by the Reports UI for daily/weekly/monthly/yearly views.
 */
data class UserPerformanceReportDto(
    val startDate: LocalDate,
    val endDate: LocalDate,
    val userPerformances: List<UserPerformanceDto>
)
